import { useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, EmptyState, PrimaryButton, SectionTitle, StatusPill } from "@/components/app-ui";
import { SyncProfileSheet } from "@/components/sync/sync-profile-sheet";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useNotes } from "@/lib/notes/notes-provider";
import { executeSync } from "@/lib/sync/sync-service";
import { useSync } from "@/lib/sync/sync-provider";
import type { SyncProfile } from "@/lib/sync/types";

export default function SyncScreen() {
  const colors = useColors(); const { profiles, bases, conflicts, saveProfile, saveBase, appendConflicts } = useSync(); const { records, deviceId, applySyncedRecords } = useNotes(); const [editing, setEditing] = useState<SyncProfile | undefined>(); const [creating, setCreating] = useState(false); const [runningId, setRunningId] = useState<string | null>(null);
  const run = async (profile: SyncProfile) => { setRunningId(profile.id); try { const result = await executeSync(profile, records, deviceId, bases.find((base) => base.profileId === profile.id)); await applySyncedRecords(result.records); await saveBase(result.base); await appendConflicts(result.conflicts); await saveProfile({ ...profile, lastSyncedAt: new Date().toISOString(), lastError: undefined }); Alert.alert("同步完成", `${result.pulled ? "已拉取" : "未拉取"} · ${result.pushed ? "已上传" : "未上传"}${result.conflicts.length ? `\n已记录 ${result.conflicts.length} 个字段冲突。` : ""}`); } catch (error) { const message = error instanceof Error ? error.message : "请检查网络与远端配置。"; await saveProfile({ ...profile, lastError: message }); Alert.alert("同步失败", message); } finally { setRunningId(null); } };
  return <ScreenContainer className="px-5"><FlatList data={profiles} keyExtractor={(profile) => profile.id} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={[styles.eyebrow, { color: colors.primary }]}>多协议数据交换</Text><Text style={[styles.title, { color: colors.text }]}>同步中心</Text><Text style={[styles.subtitle, { color: colors.muted }]}>每次同步都先比较清单，再按字段合并变化。凭据只保存在设备安全存储。</Text><SectionTitle title="同步目标" action="添加" onAction={() => setCreating(true)} /></>} renderItem={({ item }) => <ProfileCard profile={item} running={runningId === item.id} onRun={() => run(item)} onEdit={() => setEditing(item)} />} ListEmptyComponent={<EmptyState title="未配置同步目标" description="可连接 WebDAV、SFTP，或用可视化 HTTP 流程对接任意接口。" icon="arrow.triangle.2.circlepath" />} ListFooterComponent={conflicts.length ? <><SectionTitle title="最近冲突" /><Card>{conflicts.slice(0, 3).map((conflict) => <View key={conflict.id} style={styles.conflict}><IconSymbol name={"exclamationmark.triangle.fill" as never} color={colors.warning} size={17} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "800" }}>{conflict.recordTitle}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 2 }}>{conflict.fields.length} 个并发字段 · {conflict.strategy === "duplicate" ? "已创建副本" : "已按策略解决"}</Text></View></View>)}</Card></> : null} />
    <Pressable onPress={() => setCreating(true)} style={({ pressed }) => [styles.fab, { backgroundColor: colors.primary, opacity: pressed ? 0.75 : 1 }]}><IconSymbol name={"plus" as never} color="#FFF" size={23} weight="bold" /></Pressable><SyncProfileSheet visible={creating || Boolean(editing)} profile={editing} onClose={() => { setCreating(false); setEditing(undefined); }} />
  </ScreenContainer>;
}

function ProfileCard({ profile, running, onRun, onEdit }: { profile: SyncProfile; running: boolean; onRun: () => void; onEdit: () => void }) {
  const colors = useColors(); const label = profile.protocol === "http-flow" ? "HTTP 流程" : profile.protocol.toUpperCase();
  return <Card style={styles.profileCard}><Pressable onPress={onEdit}><View style={styles.profileTop}><View style={[styles.syncIcon, { backgroundColor: `${colors.primary}16` }]}><IconSymbol name={"arrow.triangle.2.circlepath" as never} color={colors.primary} size={21} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontSize: 17, fontWeight: "800" }}>{profile.name}</Text><View style={{ flexDirection: "row", gap: 7, marginTop: 5 }}><StatusPill label={label} /><StatusPill label={profile.enabled ? "已启用" : "已暂停"} tone={profile.enabled ? "success" : "neutral"} /></View></View><IconSymbol name={"chevron.right" as never} color={colors.muted} size={19} /></View></Pressable>{profile.lastError ? <View style={[styles.error, { backgroundColor: `${colors.error}12` }]}><Text numberOfLines={2} style={{ color: colors.error, fontSize: 13 }}>{profile.lastError}</Text></View> : <Text style={{ color: colors.muted, fontSize: 13 }}>{profile.lastSyncedAt ? `上次同步：${new Date(profile.lastSyncedAt).toLocaleString("zh-CN")}` : "尚未同步"}</Text>}<PrimaryButton label={running ? "正在同步…" : "立即同步"} onPress={onRun} icon="arrow.triangle.2.circlepath" disabled={running || !profile.enabled} /></Card>;
}

const styles = StyleSheet.create({ list: { gap: 11, paddingBottom: 36 }, eyebrow: { fontSize: 12, fontWeight: "800", letterSpacing: 0.7, marginTop: 7 }, title: { fontSize: 34, fontWeight: "800", letterSpacing: -1, marginTop: 4 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 7, maxWidth: 350 }, profileCard: { gap: 12 }, profileTop: { alignItems: "center", flexDirection: "row", gap: 11 }, syncIcon: { alignItems: "center", borderRadius: 13, height: 43, justifyContent: "center", width: 43 }, error: { borderRadius: 10, padding: 10 }, conflict: { alignItems: "center", flexDirection: "row", gap: 9, paddingVertical: 7 }, fab: { alignItems: "center", borderRadius: 18, bottom: 17, elevation: 5, height: 52, justifyContent: "center", position: "absolute", right: 20, shadowColor: "#000", shadowOpacity: 0.16, shadowRadius: 10, width: 52 } });
